#!/usr/bin/env bash

function doDir {
    wd="$1"
    exclude="$2"
    target="${wd}.h"
    cat <<EOF > "${target}"
#ifndef DANZUN_${wd^^}_GROUP_INCLUDE_H_INCLUDED_H
#define DANZUN_${wd^^}_GROUP_INCLUDE_H_INCLUDED_H

EOF
    for f in ${wd}/*.h; do
        pass=1
        for e in ${exclude[@]}; do
            if [[ "$e" == "$f" ]]; then
                pass=0
                break
            fi
        done
        if ((pass == 1)); then
            echo "#include \"$f\"" >> "${target}" 
        fi
    done

    printf "\n#endif\n" >> "${target}"
}

pushd ../src/ >/dev/null

coreExclude=(
    core/error.h
    core/debug.h
)

doDir "ani"
doDir "core" "$coreExclude"
doDir "math"
doDir "render"
doDir "sprite"
doDir "time"
doDir "ui"
doDir "win"

popd >/dev/null
